# This is a basic workflow to help you get started with Actions

name: Deploy Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🚀 Deploy website
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: 📂 Deploy to production server
      uses: appleboy/ssh-action@master
      env:
        HOST_REPO_PATH: ${{ secrets.HOST_REPO_PATH }}
      with:
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        use_insecure_cipher: true
        script: |
           cd "$HOST_REPO_PATH"
           git pull
